### PR TITLE
Fix segfault on exit.

### PR DESCRIPTION
**Pull request by ghost**
Using println!("hello") from a Rust function called from Lua seems to work until the program exits and seg faults.

Doing what I would expect to be the same thing works fine though. Anyone know why this happens?

Tested on macos sierra 10.12.5 and rustc 1.20.0-nightly (bf0a9e0b4 2017-07-10)

### CODE REVIEW

**Comment by Jim-Holmstroem** [comment]
Sorry for the slow response, didn't have notifications properly setup. I will take a quick look now :)

**Comment by Jim-Holmstroem** [comment]
I have no clue why this happens, but it seems to be mac specific :)
I'll gladly accept the PR as soon as you fix the compilation error:
```
diff --git a/rust/src/lib.rs b/rust/src/lib.rs
index 0812729..606d742 100644
--- a/rust/src/lib.rs
+++ b/rust/src/lib.rs
@@ -13,7 +13,8 @@ use std::io::prelude::*;
 #[no_mangle]
 pub extern fn hello() {
     // NOTE: println!("hello") causes a segfault later
-    let mut handle = io::stdout().lock();
+    let stdout = io::stdout();
+    let mut handle = stdout.lock();
     handle.write(b"hello\n").unwrap();
     handle.flush().unwrap();
 }
```

**Comment by ghost** [comment]
I applied those changes.

**Comment by Jim-Holmstroem** [comment]
hi @nick70 , sorry for the slow replay, thanks for the fix!
This project is currently superseeded by https://github.com/distil/rust_lua_ffi/ which provides automatic FFI code generation. It's really cool and relatively easy to work with, you should look it up!

**Pull request closed without merging**
